name: covered-in-snow.com
title: 'Covered in Snow'
description: 'Beautiful songs made in Sweden'
markdown: kramdown
highligther: pygments
timezone: GMT+1
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: https://covered-in-snow.com
author: Covered in Snow
gems:
    - jekyll-feed
    - jekyll-sitemap
sass:
  style: compressed
site:
  title: 'hej'
